version: '3.8'

services:
  slideshow:
    build: .
    ports:
      - "9002:3000"
    environment:
      # --- Immich Server Configuration ---
      # Replace with your Immich server's local network URL
      - NEXT_PUBLIC_IMMICH_API_URL=http://192.168.29.3:2283
      # Replace with your Immich API Key
      - NEXT_PUBLIC_IMMICH_API_KEY=isqXAFo82NCwDd99wU7LDXILBDrY2fwGRIqcHlfUdZc

      # --- Slideshow Settings (Optional) ---
      # The duration (in seconds) each image is displayed. Defaults to 5.
      - NEXT_PUBLIC_SLIDESHOW_DURATION_S=5

      # --- OpenWeatherMap API Settings ---
      - OPENWEATHER_API_KEY=YOUR_API_KEY
      - NEXT_PUBLIC_LATITUDE=28.6139
      - NEXT_PUBLIC_LONGITUDE=77.2090
    restart: unless-stopped
